version: "3.3"

services:

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./certs:/certs"
    labels:
      # enable traefik processing
      - "traefik.enable=true"

      # secure traefik internal service - API
      - "traefik.http.routers.traefik_api.entrypoints=websecure"
      - "traefik.http.routers.traefik_api.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik_api.tls=true"
      - "traefik.http.routers.traefik_api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik_api.middlewares=basic_auth"
      - "traefik.http.routers.traefik_api.service=api@internal"

      # secure traefik internal service - dashoboard
      - "traefik.http.routers.traefik_dash.entrypoints=websecure"
      - "traefik.http.routers.traefik_dash.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/`)"
      - "traefik.http.routers.traefik_dash.tls=true"
      - "traefik.http.routers.traefik_dash.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik_dash.middlewares=basic_auth"
      - "traefik.http.routers.traefik_dash.service=dashboard@internal"

      # setup http -> https redirect
      - "traefik.http.routers.httpsredir.entrypoints=web"
      - "traefik.http.routers.httpsredir.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.httpsredir.middlewares[0]=redirecttohttps"
      - "traefik.http.routers.httpsredir.service=dummy"
      - "traefik.http.services.dummy.loadBalancer.server.url=http://nowhere.neverwhere"

      # setup basic auth middleware 
      - "traefik.http.middlewares.basic_auth.basicauth.users=${BASIC_AUTH_ENTRY}"

      # https redirect
      - "traefik.http.middlewares.redirecttohttps.redirectScheme.scheme=https"

  keycloak:
    image: "jboss/keycloak"
    container_name: "keycloak"
    labels:
      # enable traefik processing
      - "traefik.enable=true"

      # secure traefik internal service - API
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOST}`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"

  apache:
    image: "php:7.2-apache"
    container_name: "apache"
    labels:
      # enable traefik processing
      - "traefik.enable=true"

      # secure traefik internal service - API
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`${APACHE_HOST}`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"

    

